[labels]
app_name = Forums

notification_topic_mention = Mentions
notification_topic_moderation_restricted = Restrictions placed on you
notification_topic_moderation_unrestricted = Restrictions lifted
