/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedFindRouteImport } from './routes/_authenticated/find'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedForumIndexRouteImport } from './routes/_authenticated/$forum/index'
import { Route as AuthenticatedForumPostRouteImport } from './routes/_authenticated/$forum/$post'
import { Route as AuthenticatedForumModerationRouteImport } from './routes/_authenticated/$forum_.moderation'
import { Route as AuthenticatedForumSettingsRouteImport } from './routes/_authenticated/$forum_.settings'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFindRoute = AuthenticatedFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForumIndexRoute = AuthenticatedForumIndexRouteImport.update({
  id: '/$forum/',
  path: '/$forum/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForumPostRoute = AuthenticatedForumPostRouteImport.update({
  id: '/$forum/$post',
  path: '/$forum/$post',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForumModerationRoute =
  AuthenticatedForumModerationRouteImport.update({
    id: '/$forum_/moderation',
    path: '/$forum/moderation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedForumSettingsRoute =
  AuthenticatedForumSettingsRouteImport.update({
    id: '/$forum_/settings',
    path: '/$forum/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/find': typeof AuthenticatedFindRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/$forum/$post': typeof AuthenticatedForumPostRoute
  '/$forum/moderation': typeof AuthenticatedForumModerationRoute
  '/$forum/settings': typeof AuthenticatedForumSettingsRoute
  '/$forum/': typeof AuthenticatedForumIndexRoute
}
export interface FileRoutesByTo {
  '/find': typeof AuthenticatedFindRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/': typeof AuthenticatedIndexRoute
  '/$forum/$post': typeof AuthenticatedForumPostRoute
  '/$forum/moderation': typeof AuthenticatedForumModerationRoute
  '/$forum/settings': typeof AuthenticatedForumSettingsRoute
  '/$forum': typeof AuthenticatedForumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/find': typeof AuthenticatedFindRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$forum/$post': typeof AuthenticatedForumPostRoute
  '/_authenticated/$forum_/moderation': typeof AuthenticatedForumModerationRoute
  '/_authenticated/$forum_/settings': typeof AuthenticatedForumSettingsRoute
  '/_authenticated/$forum/': typeof AuthenticatedForumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/find'
    | '/saved'
    | '/$forum/$post'
    | '/$forum/moderation'
    | '/$forum/settings'
    | '/$forum/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/find'
    | '/saved'
    | '/'
    | '/$forum/$post'
    | '/$forum/moderation'
    | '/$forum/settings'
    | '/$forum'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/find'
    | '/_authenticated/saved'
    | '/_authenticated/'
    | '/_authenticated/$forum/$post'
    | '/_authenticated/$forum_/moderation'
    | '/_authenticated/$forum_/settings'
    | '/_authenticated/$forum/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/find': {
      id: '/_authenticated/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof AuthenticatedFindRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$forum/': {
      id: '/_authenticated/$forum/'
      path: '/$forum'
      fullPath: '/$forum/'
      preLoaderRoute: typeof AuthenticatedForumIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$forum/$post': {
      id: '/_authenticated/$forum/$post'
      path: '/$forum/$post'
      fullPath: '/$forum/$post'
      preLoaderRoute: typeof AuthenticatedForumPostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$forum_/moderation': {
      id: '/_authenticated/$forum_/moderation'
      path: '/$forum/moderation'
      fullPath: '/$forum/moderation'
      preLoaderRoute: typeof AuthenticatedForumModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$forum_/settings': {
      id: '/_authenticated/$forum_/settings'
      path: '/$forum/settings'
      fullPath: '/$forum/settings'
      preLoaderRoute: typeof AuthenticatedForumSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFindRoute: typeof AuthenticatedFindRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedForumPostRoute: typeof AuthenticatedForumPostRoute
  AuthenticatedForumModerationRoute: typeof AuthenticatedForumModerationRoute
  AuthenticatedForumSettingsRoute: typeof AuthenticatedForumSettingsRoute
  AuthenticatedForumIndexRoute: typeof AuthenticatedForumIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFindRoute: AuthenticatedFindRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedForumPostRoute: AuthenticatedForumPostRoute,
  AuthenticatedForumModerationRoute: AuthenticatedForumModerationRoute,
  AuthenticatedForumSettingsRoute: AuthenticatedForumSettingsRoute,
  AuthenticatedForumIndexRoute: AuthenticatedForumIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
